# Generated by Django 3.2.12 on 2022-02-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='current_price',
            field=models.FloatField(blank=True),
        ),
    ]
