# Generated by Django 3.2.12 on 2022-03-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_current_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('price_difference', '-created')},
        ),
    ]
