# Generated by Django 3.2.12 on 2022-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='set_price',
            field=models.FloatField(default=0),
        ),
    ]
