# Generated by Django 3.2.12 on 2022-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_set_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='email_id',
            field=models.CharField(default='kaustubh.tripathi6794@gmail.com', max_length=800),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.CharField(default='Admin', max_length=400),
        ),
    ]
