# Generated by Django 3.2.12 on 2022-03-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20220318_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='user',
            new_name='user1',
        ),
    ]
