# Generated by Django 3.2.12 on 2022-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_rename_user_link_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Admin', max_length=400)),
                ('email_id', models.CharField(default='kaustubh.tripathi6794@gmail.com', max_length=800)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='user1',
        ),
        migrations.AddField(
            model_name='link',
            name='user_info',
            field=models.ManyToManyField(to='links.Profile'),
        ),
    ]
