# Generated by Django 3.2.12 on 2022-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20220318_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_id',
            field=models.CharField(blank=True, default='kaustubh.tripathi6794@gmail.com', max_length=800),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='Admin', max_length=400),
        ),
    ]
